---
title: "Problem Set 1 (Template)"
author: "Kirk Bansak"
date: "January 31, 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 1

### 1.1

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 1.2

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 1.3

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 1.4

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 1.5

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


## Part 2

### 2.1

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 2.2

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 2.3

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


### 2.4

Any text/explanation...

```{r}
some_code <- c(1,2,3,4,5)
some_code
```


## Part 3

Any text/explanation...